### ISSUE TITLE
refresh not refreshing

### ISSUE THREAD

**Issue by RatatoskofRagnarok** [CyrilCharlier/CScript#12]
in new version, using the refresh button does not refresh the info.
have to open something to see new items in inventory.

**Comment by CyrilCharlier** [comment]
Hello,

It is refreshing, it doesn't refresh the inventory tab. Will be OK in the next release

**Comment by RatatoskofRagnarok** [comment]
thanks
it does not seem to be refreshing the attacks tab either
sometimes when attacks return home, the timer restarts and it shows them as still marching. refreshing used to clear these marches and it doesn't now.

sorry to be sending you so many bugs, i have been collecting them from the doa scripts group, as i seem to be one of the few with a github account

**Comment by CyrilCharlier** [comment]
No problem, but i don"t think it is the same problem. Will open a new issue with your comment.
