### ISSUE TITLE
abyssal 

### ISSUE THREAD

**Issue by cwaj2011** [CyrilCharlier/CScript#15]
when i got the abyssal in my kingdom the script name it undefined. and the auto build stop there and will not build anything , i am useing doa power tools teamwork v16.13a overarch. is there any thing i can do to fix this?

**Comment by CyrilCharlier** [comment]
Hello, sorry it is not a Github for teamwork. You can go to this group to post your question  : https://www.facebook.com/groups/274006229470828/

thanks

**Comment by cwaj2011** [comment]
lol there the ones who told me to go here lol

**Comment by CyrilCharlier** [comment]
hum, very strange, it is a group for Teamwork only ! in french ;)

**Comment by cwaj2011** [comment]
lol i siad same thing lol
