### ISSUE TITLE
Fails to load (hangs at initializing autocollect, etc)

### ISSUE THREAD

**Issue by KwikOne** [CyrilCharlier/CScript#22]
If the outposts are built out of order. i.e. Abyssal but no wind, it will fail in checks for the Abyssal and Leviathan outposts since the cities array will have an entry missing. 
This is because the code needs to have error checking when checking the cities array in case this scenario occurs (which it will)

**Comment by CyrilCharlier** [comment]
Just publish a new version , just wait for Chrome Web Store take it

**Comment by CyrilCharlier** [comment]
Closed with this PR : https://github.com/CyrilCharlier/CScript/commit/b47445e5fbaa6d0e1b7cf66bb7e268f7785b5ec2
