### ISSUE TITLE
Forge inventory equipment attributes

### ISSUE THREAD

**Issue by KwikOne** [CyrilCharlier/CScript#29]
@CyrilCharlier 
It  used to be that when the mouse was over the forge inventory equipment name the attributes would show up (as a popup). This behavior no longer occurs. Now the attributes only show up when the mouse is just past the name (1 space past). The problem is at line 23536 and line 23624. At line 23636 it should read as...
```javascript
 + '	<td>&nbsp;'+getInfoEquipment(items[i])+translate(items[i].name)+'&nbsp;'+'" />'+'&nbsp;</td>'
```
instead of
```javascript
+ '	<td>&nbsp;'+translate(items[i].name)+'&nbsp;'+getInfoEquipment(items[i])+'&nbsp;</td>'
```

**AND** line 23624 should read as
```javascript
	return '<span class="'+UID[classStat]+'" title="'+display';
```
*instead of*
```javascript
	return '<span class="'+UID[classStat]+'" title="'+display+'" />';
```

This will allow the attributes to show up anywhere over the equipment name instead of just past the name since the name is within the span

**Comment by KwikOne** [comment]
Hmm, on second look, it appears that the background image for the span is not showing for some reason. If the image showed it would then make it easier to determine where to put the cursor to see the attributes. (In trying to directly access the image it continues to get an error (connection timed out))

**Comment by KwikOne** [comment]
If I tyr to direct access the icon/image ( http://www.calcium-pro-tool.com/script/icons/number2.png ) then the server returns a 404/Not Found error. So it seems there is 2 problems with the server, one the image isnt there and two the server has a problem with https connections

**Comment by CyrilCharlier** [comment]
Yes i have problem with R&Y, so i have reset all my server. I must put again some image

**Comment by CyrilCharlier** [comment]
Hi,

Can you tell me if it is OK now ? All images are on the server

**Comment by KwikOne** [comment]
Yes, it is now OK. 
Merci

-----Original Message-----
