### ISSUE TITLE
Encamped Troops in Spec Op

### ISSUE THREAD

**Issue by Shanra** [CyrilCharlier/CScript#32]
It would be very helpful if the information on each group of encamped troops told us which troops and how many of them belong to each encampment. Without loading the game to check, it's impossible to know which res we are bringing back to our capital.

![specopres](https://cloud.githubusercontent.com/assets/16618175/12213720/c021e342-b64b-11e5-847f-8530d08b5e68.png)

**Comment by CyrilCharlier** [comment]
when you put your mouse on the line : 
![image](https://cloud.githubusercontent.com/assets/11455745/23465107/80523de4-fe97-11e6-88f8-36178c54df59.png)
