### ISSUE TITLE
Script won't load anymore

### ISSUE THREAD

**Issue by Ga8tor** [CyrilCharlier/CScript#33]
Script stopped loading on 1/29/16.

**Comment by Kivagyoq** [comment]
The very same here. It is not loading since that time (1/29/16). May has it something to do with the fact that I have winXP and Chrome won't support it anymore? Calciumscript keeps getting stuck during "fetching translation matrix" and there's no shield icon on address bar to avoid this...

**Comment by CyrilCharlier** [comment]
Hi : 

Start Chrome with the switch

--allow-running-insecure-content
or add this to Chrome's shortcut like so:

chrome.exe --allow-running-insecure-content
and it will load insecure content automatically

**Comment by Kivagyoq** [comment]
Greetings

Thx. for quick answer but it seems I proved to be either blind or idiot.:) Does "switch" mean "Customize and control Google Chrome" button and "settings" tab in it? Anyhow I can't find any option to  "--allow-running-insecure-content" and even don't know how to add shortcuts to Chrome... Sorry...

**Comment by CyrilCharlier** [comment]
No problem, watch this video : http://screenpresso.com/=nxf1f

**Comment by Kivagyoq** [comment]
Thank you. It's working now...:)

**Comment by CyrilCharlier** [comment]
Super !

**Comment by Ga8tor** [comment]
Working for me now you, thank you for the info!
