### ISSUE TITLE
Script not loading at all

### ISSUE THREAD

**Issue by annielayer** [CyrilCharlier/CScript#34]
Stopped on the translation matrix, hangs there, then stops altogether. There are a lot of comments as well on the Chrome store.

**Comment by jacob2009** [comment]
I am having the same problem, have you found out how to fix it??

**Comment by annielayer** [comment]
In the Properties of the Chrome browser, change the target to:

  "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-running-insecure-content 

and it works in Chrome. You have to restart everything after making the change.

**Comment by gregoryrenard** [comment]
j'ai essayé de fair ce que vous ecrivez mais je ne trouve pas j'ai un mac est quand je click droit je n'obtiens pas les proprietés quelqu'un pour m'aider svp

**Comment by CyrilCharlier** [comment]
Hello

on a mac, you can create an applescript application in applesript editor with following contents:

do shell script "'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --allow-running-insecure-content > /dev/null 2>&1 &"

when you save it as an application, you can assign chrome icon to it :)

**Comment by timmyuk** [comment]
how do you get into chrome properties?

**Comment by gregoryrenard** [comment]
je n'arrive pas a trouver les propriétés dans chrome pouvez vous m'indiquer svp

**Comment by CyrilCharlier** [comment]
would be ok now
