### ISSUE TITLE
Script not loading at all again

### ISSUE THREAD

**Issue by annielayer** [CyrilCharlier/CScript#37]
Same problem, had temporary fix but now hanging up at the translation matrix again.

**Comment by ghisturm** [comment]
Same here!!!

**Comment by Floydacus** [comment]
I Also have same problem ,fixed it once buy restore an early save point , but now wont work this time tried clearing and reloading every thing and no luck

**Comment by Fighter6869** [comment]
same

**Comment by CyrilCharlier** [comment]
Now ok
