### ISSUE TITLE
build task function not working since 5/20 afternoon

### ISSUE THREAD

**Issue by Ga8tor** [CyrilCharlier/CScript#39]
Yesterday I noticed the build task function was no longer working - the build automatically button lost it's label and doesn't work.  Since that time I think I've had two version updates but it still isn't working.  I ran cc cleaner a few times, restarted, etc...but no change still not working.

Any ideas?

Also any way someone can add an auto-click feature for the inventory items (esp the chests)!

Thanks,
Wiz

**Comment by CyrilCharlier** [comment]
Now it is working
