### ISSUE TITLE
Fortuna Tab

### ISSUE THREAD

**Issue by CyrilCharlier** [CyrilCharlier/CScript#7]
Any ideas how to get fortuna to actually play fortunas? it runs and i have set it up to do only when at least 1 item of the 6 i have selected are there. But after running 9000 fortunas it has not played one single game it simple don't choose anything. Is there a fix for this? I have 2500 fortunas and 2k medallions i would like to have played émoticône wink thanx in advance

**Comment by RMZahn** [comment]
i had the same problem
with the "0" as the "max" it dont collect anything
i set the amount of fortunas/medallions what i have and it works

just until i come to the fortuna-tab the computer freezes for ~1 minute
(same if i change from fortuna to medallions)

**Comment by CyrilCharlier** [comment]
for the freeze it is "normal" : the must populate de 6 dropdown liste with hundreds of items and after the browser must render them

**Comment by RMZahn** [comment]
ok, thx :-)
